admin_cards:
    pattern:  /
    defaults: { _controller: "DtdbCardsBundle:Cards:index" }

admin_cards_show:
    pattern:  /{id}/show
    defaults: { _controller: "DtdbCardsBundle:Cards:show" }

admin_cards_new:
    pattern:  /new
    defaults: { _controller: "DtdbCardsBundle:Cards:new" }

admin_cards_create:
    pattern:  /create
    defaults: { _controller: "DtdbCardsBundle:Cards:create" }
    requirements: { _method: post }

admin_cards_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DtdbCardsBundle:Cards:edit" }

admin_cards_update:
    pattern:  /{id}/update
    defaults: { _controller: "DtdbCardsBundle:Cards:update" }
    requirements: { _method: post }

admin_cards_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DtdbCardsBundle:Cards:delete" }
    requirements: { _method: post }
