admin_type:
    path:     /
    defaults: { _controller: "DtdbCardsBundle:Type:index" }

admin_type_show:
    path:     /{id}/show
    defaults: { _controller: "DtdbCardsBundle:Type:show" }

admin_type_new:
    path:     /new
    defaults: { _controller: "DtdbCardsBundle:Type:new" }

admin_type_create:
    path:     /create
    defaults: { _controller: "DtdbCardsBundle:Type:create" }
    requirements: { _method: post }

admin_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "DtdbCardsBundle:Type:edit" }

admin_type_update:
    path:     /{id}/update
    defaults: { _controller: "DtdbCardsBundle:Type:update" }
    requirements: { _method: post|put }

admin_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "DtdbCardsBundle:Type:delete" }
    requirements: { _method: post|delete }
